import {chromium} from '/home/dev/vpr-sync/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.ALGEBRA_URL||'http://127.0.0.1:8947/';
const browser=await chromium.launch({executablePath:'/home/dev/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.waitForSelector('.task');
assert.equal(await page.locator('.level-button').count(),7);
assert.equal(await page.locator('.group-button').count(),14);
await page.screenshot({path:'/tmp/algebra-desktop.png',fullPage:false});
await page.locator('[data-add]').first().click();assert.equal(await page.locator('.lesson-row').count(),1);
await page.reload();await page.waitForSelector('.task');assert.equal(await page.locator('.lesson-row').count(),1);
await page.locator('#combination-toggle').click();await page.locator('#mixed-preset').click();assert.ok(await page.locator('.task').count()>0);
assert.equal(await page.locator('.tag-remove').count(),3);
await page.locator('.answer-details summary').first().click();assert.ok(await page.locator('.answer-details[open] .katex').count()>0);
await page.locator('[data-add]').first().click();assert.equal(await page.locator('.lesson-row').count(),2);
await page.locator('[data-variants]').first().click();assert.ok(await page.locator('.task').count()>1);
const downloadPromise=page.waitForEvent('download');await page.click('#export');const dl=await downloadPromise;const path=await dl.path();const exported=JSON.parse(fs.readFileSync(path,'utf8'));assert.equal(exported.tasks.length,2);
await page.click('#student-link');const link=await page.evaluate(()=>navigator.clipboard.readText());assert.ok(link.includes('sheet='));
const sheet=await ctx.newPage();await sheet.goto(link);await sheet.waitForSelector('.sheet .task');assert.equal(await sheet.locator('.sheet .task').count(),2);assert.equal(await sheet.locator('.answer-body').count(),0);
await sheet.pdf({path:'/tmp/algebra-student-sheet.pdf',format:'A4'});
await page.evaluate(()=>{window.print=()=>{};});await page.click('#print');assert.equal(await page.locator('#print-area .task').count(),2);assert.equal(await page.locator('#print-area .answer-key').count(),0);
await page.check('#print-answers');await page.click('#print');assert.equal(await page.locator('#print-area .answer-key .task').count(),2);
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base);await mobile.waitForSelector('.task');await mobile.screenshot({path:'/tmp/algebra-mobile.png',fullPage:false});
assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await mobile.locator('[data-add]').first().click();await mobile.click('#collection-toggle');assert.equal(await mobile.locator('#collection.open').count(),1);assert.equal(await mobile.locator('.lesson-row').count(),1);assert.equal(await mobile.locator('main').evaluate(el=>el.inert),true);for(let i=0;i<25;i++){await mobile.keyboard.press('Tab');assert.equal(await mobile.evaluate(()=>!!document.activeElement.closest('#collection')),true);}await mobile.screenshot({path:'/tmp/algebra-mobile-collection.png',fullPage:false});await mobile.click('#close-collection');
assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,desktop:'1440x1000',mobile:'390x844',checks:['filters','combination','variants','selection','reload','answers','export','student-link','print','mobile'],errors}));await browser.close();
