import {filterTasks,representative,restoreSelection} from './model.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(name){const path={close:'M6 6l12 12M18 6 6 18',up:'m6 14 6-6 6 6',check:'m5 12 4 4L19 6'}[name];return `<svg class="action-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;}
let bank,byId,bySkill,selected=[],page=1,template='',extra=[],current=[],shown=[];
const state={group:'g3',skills:[],level:'',grade:'',search:'',mixed:false};const SIZE=18,STORE='algebra-bank-lesson-v1';
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
function quantity(n,one,few,many){const v=n%100;return `${n.toLocaleString('ru')} ${v>=11&&v<=14?many:n%10===1?one:n%10>=2&&n%10<=4?few:many}`;}
function math(s){try{return katex.renderToString(String(s),{throwOnError:true,strict:'ignore',trust:false,output:'htmlAndMathml'});}catch{return `<span>${esc(s)}</span>`;}}
function graphHTML(g){
 const W=340,H=245,P=28,lo=g.range[0],hi=g.range[1];let yl=lo,yh=hi;
 if(g.curves.some(c=>c.kind==='parabola')){yl=-2;yh=Math.max(lo*lo,hi*hi)+2;}
 else{const ys=g.curves.flatMap(c=>[c.a*lo+c.b,c.a*hi+c.b]);yl=Math.min(lo,...ys);yh=Math.max(hi,...ys);}
 const X=x=>P+(x-lo)/(hi-lo)*(W-2*P),Y=y=>H-P-(y-yl)/(yh-yl)*(H-2*P);let svg='';
 const xs=Math.max(1,Math.ceil((hi-lo)/10)),ys=Math.max(1,Math.ceil((yh-yl)/8));
 for(let v=Math.ceil(lo/xs)*xs;v<=hi;v+=xs)svg+=`<path class="grid-line" d="M${X(v)} ${P}V${H-P}" stroke="#314156"/><text x="${X(v)}" y="${Y(0)+14}" text-anchor="middle" font-size="9" fill="#bac9da">${v}</text>`;
 for(let v=Math.ceil(yl/ys)*ys;v<=yh;v+=ys)svg+=`<path class="grid-line" d="M${P} ${Y(v)}H${W-P}" stroke="#314156"/>${v===0?'':`<text x="${X(0)-6}" y="${Y(v)+3}" text-anchor="end" font-size="9" fill="#bac9da">${v}</text>`}`;
 svg+=`<path class="axis" d="M${P} ${Y(0)}H${W-P}M${X(0)} ${P}V${H-P}" stroke="#a8b8cc"/><text x="${W-P+8}" y="${Y(0)+4}" font-size="11" fill="#edf2f8">x</text><text x="${X(0)+7}" y="${P-9}" font-size="11" fill="#edf2f8">y</text>`;
 g.curves.forEach((c,j)=>{let d='';for(let i=0;i<=160;i++){let xx=lo+(hi-lo)*i/160,yy=c.kind==='parabola'?xx*xx:c.a*xx+c.b;d+=(i?'L':'M')+X(xx).toFixed(2)+' '+Y(yy).toFixed(2)+' ';}svg+=`<path class="curve" d="${d}" stroke="${j?'#8adebe':'#9ac9ff'}" stroke-width="2" fill="none"/>`;});
 return `<svg class="graph" viewBox="0 0 ${W} ${H}" role="img" aria-label="Координатная плоскость с графиком, оси и деления подписаны">${svg}</svg>`;
}
function save(){try{localStorage.setItem(STORE,JSON.stringify(selected));localStorage.setItem(STORE+'-title',$('lesson-title').value);}catch{toast('Браузер не разрешил сохранение. Скачайте подборку, чтобы не потерять её.');}}
function groupsRender(){const counts=new Map();for(const t of bank.tasks){let g=bySkill.get(t.primary).group;counts.set(g,(counts.get(g)||0)+1);}
 $('groups').innerHTML=[{id:'',title:'Весь банк'},...bank.groups].map(g=>`<button class="group-button ${state.group===g.id?'active':''}" data-group="${g.id}" aria-pressed="${state.group===g.id}"><span>${esc(g.title)}</span><small>${(g.id?counts.get(g.id):bank.tasks.length).toLocaleString('ru')}</small></button>`).join('');}
function skillOptions(){const list=bank.skills.filter(s=>!state.group||s.group===state.group);$('skill').innerHTML='<option value="">Все навыки раздела</option>'+list.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join('');}
function levelsRender(){ $('levels').innerHTML=['Все',...bank.levels].map((n,i)=>`<button class="level-button ${state.level===(i?String(i):'')?'active':''}" data-level="${i||''}" aria-pressed="${state.level===(i?String(i):'')}">${i?`<strong>${i}</strong> <span>${esc(n)}</span>`:'Все уровни'}</button>`).join('');}
function tagsRender(){$('selected-tags').innerHTML=extra.map(id=>`<button class="tag-remove" data-remove-tag="${id}">${esc(bySkill.get(id).title)} ${icon('close')}</button>`).join('');}
function taskHTML(t){let count=bank.templateCounts[t.template];return `<article class="task" data-task="${t.id}"><div class="task-top"><span class="level-badge" data-level="${t.level}">${t.level} · ${esc(bank.levels[t.level-1])}</span><span>${esc(bySkill.get(t.primary).title)}</span>${t.manual?'<span class="manual">С объяснением</span>':''}<span class="task-id">${esc(t.id.slice(-6))}</span></div><p class="task-prompt">${esc(t.prompt)}</p>${t.math?`<div class="formula">${math(t.math)}</div>`:''}${t.graph?graphHTML(t.graph):''}<div class="task-tags">${t.skills.slice(1).map(id=>`<button class="task-tag" data-tag="${id}" title="Найти задания по навыку">${esc(bySkill.get(id).title)}</button>`).join('')}</div><div class="task-actions"><details class="answer-details"><summary>Ответ и разбор</summary><div class="answer-body"><span class="math">${math(t.answer)}</span><p class="solution">${esc(t.solution)}</p>${t.manual?'<p class="solution">Объяснение проверяет учитель.</p>':''}</div></details><div class="task-bottom">${count>1&&!template?`<button class="variants-button" data-variants="${t.template}">${count} вариантов</button>`:''}<button class="add-button ${selected.includes(t.id)?'selected':''}" data-add="${t.id}" aria-pressed="${selected.includes(t.id)}">${selected.includes(t.id)?'В подборке':'В подборку'}</button></div></div></article>`;}
function render(){state.skills=[...new Set([$('skill').value,...extra].filter(Boolean))];current=filterTasks(bank.tasks,state,bank.skills);if(template)current=current.filter(t=>t.template===template);let list=$('view').value==='types'&&!template?representative(current):current;const pages=Math.max(1,Math.ceil(list.length/SIZE));page=Math.min(page,pages);shown=list.slice((page-1)*SIZE,page*SIZE);
 $('page-title').textContent=template?'Варианты одной конструкции':(state.group?bank.groups.find(g=>g.id===state.group).title:'Банк алгебры');$('page-description').textContent=extra.length?'Задания, в которых используются все выбранные навыки.':'Выберите навык и уровень. Добавляйте задания в подборку урока.';
 $('total').textContent=`${bank.skills.length} навыков`;
 $('result-count').textContent=`${quantity(current.length,'задание','задания','заданий')} · ${quantity(new Set(current.map(t=>t.template)).size,'конструкция','конструкции','конструкций')}`;
 $('tasks').innerHTML=shown.length?shown.map(taskHTML).join(''):'<div class="empty"><h2>Таких заданий пока нет</h2><p>Попробуйте другой уровень или уберите один из навыков.</p><button data-reset="true">Сбросить фильтры</button></div>';
 $('add-page').disabled=!shown.length;
 $('pagination').innerHTML=`${template?'<button id="back-types">К списку конструкций</button>':''}${pages>1?`<button data-page="${page-1}" ${page===1?'disabled':''}>Назад</button><span>${page} / ${pages}</span><button data-page="${page+1}" ${page===pages?'disabled':''}>Далее</button>`:''}`;
 levelsRender();groupsRender();tagsRender();}
function collectionRender(){let ts=selected.map(id=>byId.get(id)).filter(Boolean);$('top-count').textContent=ts.length;$('collection-meta').textContent=ts.length?`${quantity(ts.length,'задание','задания','заданий')} · ${quantity(new Set(ts.map(t=>t.primary)).size,'навык','навыка','навыков')}`:'Выберите задания из банка.';$('collection-empty').hidden=!!ts.length;
 $('lesson-list').innerHTML=ts.map((t,i)=>`<li class="lesson-row"><span class="lesson-number">${i+1}.</span><div class="lesson-text"><small>Уровень ${t.level}</small>${t.math?`<span class="math">${math(t.math)}</span>`:esc(t.prompt)}<span>${esc(bySkill.get(t.primary).title)}</span></div><div class="lesson-tools"><button data-up="${i}" aria-label="Переместить задание ${i+1} выше" ${i===0?'disabled':''}>${icon('up')}</button><button data-remove="${t.id}" aria-label="Удалить задание ${i+1}">${icon('close')}</button></div></li>`).join('');
 ['print','export','copy','clear','student-link'].forEach(id=>$(id).disabled=!ts.length);document.querySelectorAll('[data-add]').forEach(b=>{const yes=selected.includes(b.dataset.add);b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);b.textContent=yes?'В подборке':'В подборку';});}
function toggleTask(id){if(selected.includes(id))selected=selected.filter(x=>x!==id);else selected.push(id);save();collectionRender();}
function reset(){Object.assign(state,{group:'',skills:[],level:'',grade:'',search:'',mixed:false});extra=[];template='';page=1;$('search').value='';$('grade').value='';$('view').value='types';skillOptions();render();}
function sheetHTML(ts,title,answers=false){return `<section class="sheet"><h1>${esc(title)}</h1><p class="print-note">Алгебра · ${ts.length} заданий</p>${ts.map((t,i)=>`<article class="task"><p class="task-prompt"><span class="task-number">${i+1}.</span> ${esc(t.prompt)}</p>${t.math?`<div class="formula">${math(t.math)}</div>`:''}${t.graph?graphHTML(t.graph):''}<div class="writing-space"></div></article>`).join('')}${answers?`<section class="answer-key"><h2>Ответы и разборы</h2>${ts.map((t,i)=>`<article class="task"><h3>${i+1}.</h3><div class="answer-body"><span class="math">${math(t.answer)}</span><p class="solution">${esc(t.solution)}</p></div></article>`).join('')}</section>`:''}</section>`;}
async function copyText(s,success){try{await navigator.clipboard.writeText(s);toast(success);}catch{toast('Не удалось скопировать. Используйте выгрузку или печать.');}}
function exportJSON(){const payload={format:'palomig-algebra-lesson-v1',title:$('lesson-title').value,tasks:selected.map(id=>byId.get(id)),created_at:new Date().toISOString()};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='algebra-lesson.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function start(){
 try{const response=await fetch('bank.json');if(!response.ok)throw Error('bank');bank=await response.json();byId=new Map(bank.tasks.map(t=>[t.id,t]));bySkill=new Map(bank.skills.map(s=>[s.id,s]));bank.templateCounts={};bank.tasks.forEach(t=>bank.templateCounts[t.template]=(bank.templateCounts[t.template]||0)+1);
 const query=new URLSearchParams(location.search);if(query.has('sheet')){const ids=[...new Set(query.get('sheet').split(','))];const ts=ids.map(id=>byId.get(id)).filter(Boolean);const title=query.get('title')||'Алгебра · практика';document.body.classList.add('student-sheet');document.querySelector('.workspace').remove();document.querySelector('.topbar').remove();$('print-area').remove();const root=document.createElement('div');root.innerHTML=sheetHTML(ts,title);document.body.prepend(root);const bar=document.createElement('div');bar.className='sheet-head';bar.innerHTML='<p>Лист заданий</p><button class="primary" id="sheet-print">Печать / PDF</button>';root.querySelector('.sheet').prepend(bar);if(ts.length!==ids.length){const p=document.createElement('p');p.textContent='Некоторые задания в ссылке не найдены.';root.querySelector('.sheet').prepend(p);}if(!ts.length)root.querySelector('.sheet').insertAdjacentHTML('beforeend','<p>В листе нет доступных заданий. Попросите учителя прислать новую ссылку.</p>');$('sheet-print').onclick=()=>window.print();return;}
 try{selected=restoreSelection(localStorage.getItem(STORE),new Set(byId.keys()));$('lesson-title').value=localStorage.getItem(STORE+'-title')||'Алгебра · практика';}catch{}
 skillOptions();$('extra-skill').innerHTML='<option value="">Выберите из списка</option>'+bank.groups.map(g=>`<optgroup label="${esc(g.title)}">${bank.skills.filter(s=>s.group===g.id).map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join('')}</optgroup>`).join('');render();collectionRender();
 }catch(e){$('tasks').innerHTML='<div class="empty"><h2>Не удалось загрузить базу</h2><p>Проверьте соединение и обновите страницу.</p><button onclick="location.reload()">Повторить</button></div>';$('result-count').textContent='Ошибка загрузки';console.error(e);return;}
 $('groups').onclick=e=>{const b=e.target.closest('[data-group]');if(!b)return;state.group=b.dataset.group;extra=[];template='';page=1;skillOptions();render();};
 $('levels').onclick=e=>{const b=e.target.closest('[data-level]');if(!b)return;state.level=b.dataset.level;page=1;render();};
 let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.search=$('search').value;page=1;template='';render();},180);};
 $('grade').onchange=()=>{state.grade=$('grade').value;page=1;render();};$('skill').onchange=()=>{page=1;template='';render();};$('view').onchange=()=>{page=1;template='';render();};$('reset').onclick=reset;
 $('combination-toggle').onclick=()=>{let open=$('combination').hidden;$('combination').hidden=!open;$('combination-toggle').setAttribute('aria-expanded',open);};
 function addTag(id){if(!id)return;const prev=$('skill').value;state.group='';skillOptions();if(prev&&!extra.includes(prev))extra.push(prev);if(!extra.includes(id))extra.push(id);template='';page=1;$('combination').hidden=false;$('combination-toggle').setAttribute('aria-expanded','true');render();}
 $('add-skill').onclick=()=>addTag($('extra-skill').value);$('selected-tags').onclick=e=>{const b=e.target.closest('[data-remove-tag]');if(b){extra=extra.filter(id=>id!==b.dataset.removeTag);page=1;render();}};
 $('mixed-preset').onclick=()=>{state.group='';state.level='';state.grade='';state.search='';$('search').value='';$('grade').value='';skillOptions();extra=['A051','A055','A007'];page=1;template='';render();};
 $('tasks').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add)toggleTask(b.dataset.add);if(b.dataset.variants){template=b.dataset.variants;page=1;render();}if(b.dataset.tag)addTag(b.dataset.tag);if(b.dataset.reset)reset();};
 $('pagination').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='back-types'){template='';page=1;render();}else if(b.dataset.page){page=Number(b.dataset.page);render();$('content').scrollIntoView({behavior:'instant'});}};
 $('add-page').onclick=()=>{selected=[...new Set([...selected,...shown.map(t=>t.id)])];save();collectionRender();toast('Показанные задания добавлены в подборку');};
 $('lesson-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.remove)selected=selected.filter(id=>id!==b.dataset.remove);if(b.dataset.up){const i=Number(b.dataset.up);if(i>0)[selected[i-1],selected[i]]=[selected[i],selected[i-1]];}save();collectionRender();};
 $('lesson-title').oninput=save;$('clear').onclick=()=>{if(!confirm('Удалить все задания из этой подборки?'))return;selected=[];save();collectionRender();};
 function setCollection(open){const panel=$('collection');panel.classList.toggle('open',open);document.querySelectorAll('.topbar,.sidebar,main').forEach(el=>el.inert=open);document.body.style.overflow=open?'hidden':'';if(open){panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');$('close-collection').focus();}else{panel.removeAttribute('role');panel.removeAttribute('aria-modal');$('collection-toggle').focus();}}
 $('collection-toggle').onclick=()=>setCollection(!$('collection').classList.contains('open'));$('close-collection').onclick=()=>setCollection(false);document.addEventListener('keydown',e=>{if(!$('collection').classList.contains('open'))return;if(e.key==='Escape'){setCollection(false);return;}if(e.key==='Tab'){const items=[...$('collection').querySelectorAll('button:not([disabled]),input,select,a[href]')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});matchMedia('(min-width:1251px)').addEventListener('change',e=>{if(e.matches&&$('collection').classList.contains('open'))setCollection(false);});
 $('export').onclick=exportJSON;$('copy').onclick=()=>copyText($('lesson-title').value+'\n\n'+selected.map((id,i)=>{let t=byId.get(id);return `${i+1}. ${t.prompt}\n${t.math}`;}).join('\n\n'),'Задания скопированы без ответов');
 $('student-link').onclick=()=>{const url=new URL(location.href);url.search='';url.searchParams.set('sheet',selected.join(','));url.searchParams.set('title',$('lesson-title').value);copyText(url.href,'Ссылка на лист заданий скопирована');};
 $('print').onclick=()=>{$('print-area').innerHTML=sheetHTML(selected.map(id=>byId.get(id)),$('lesson-title').value,$('print-answers').checked);window.print();};
}
start();
